name: Bug Report
description: Report a non-security sensitive bug in Keycloak
labels: ["kind/bug", "status/triage"]
body:
  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Affected area
      options:
        - 
        - account/api
        - account/ui
        - adapter/fuse
        - adapter/java-cli
        - adapter/javascript
        - adapter/jee
        - adapter/jee-saml
        - adapter/spring
        - admin/api
        - admin/cli
        - admin/fine-grained-permissions
        - admin/ui
        - admin/client-java
        - admin/client-js
        - authentication
        - authentication/webauthn
        - authorization-services
        - ci
        - core
        - dependencies
        - dist/quarkus
        - docs
        - identity-brokering
        - import-export
        - infinispan
        - ldap
        - login/ui
        - oidc
        - oid4vc
        - operator
        - saml
        - storage
        - testsuite
        - token-exchange
        - translations
        - user-profile
        - welcome/ui
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: Provide a clear and concise description of what the problem is.
    validations:
      required: true
  - type: checkboxes
    id: regression
    attributes:
      label: Regression
      description: Was the issue introduced only after upgrading Keycloak, and it worked as expected in the past?
      options:
        - label: The issue is a regressions
