name: Bug Report
description: Report a non-security sensitive bug in Keycloak
labels: ["kind/bug", "status/triage"]
body:
  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Affected area
      options:
        - oidc
        - saml
  - type: textarea
    attributes:
      label: Describe the bug
      description: Provide a clear and concise description of what the problem is.
    validations:
      required: true
